#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Draws BentoBar's icons as Android vector drawables.

The mark is a bento box seen from above: a long compartment on top that is a status bar (a ‹ and
three item dots cut out of it), and three compartments below for the items it holds. Rice,
salmon, tamago and edamame in an ink-blue box. The ‹ and dots are real holes (evenOdd), so the
single-colour versions (themed icon, header, Quick Settings tile) keep them. Everything sits
inside the adaptive icon's 66 dp safe zone.

Writes app/src/main/res/drawable/:
  ic_launcher_background.xml   the ink gradient
  ic_launcher_foreground.xml   the compartments (adaptive icon, 108 dp)
  ic_launcher_monochrome.xml   the compartments in one colour (themed icons)
  ic_bentobar.xml              the mark at 24 dp (settings header, About, the ‹ menu)
  ic_tile_bar.xml              the mark at 24 dp for the Quick Settings tile
and docs/images/icon.png (512 px, for the README) when rsvg-convert is available.

    python3 tools/logo.py
"""
import math
import os
import pathlib
import shutil
import subprocess
import tempfile

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res/drawable"
INK = ("#FF34397E", "#FF181B45")  # box, top left to bottom right
# Compartments top to bottom: bar (rice), tall (salmon), small (tamago), small (edamame).
FOOD = [("#FFFFFDF7", "#FFF1EBDD"), ("#FFFF7E5F", "#FFF4533F"), ("#FFFFD25A", "#FFFDB62F"), ("#FF74CC6E", "#FF4DB05A")]
# The grid on the 108 dp canvas, drawn at 0.92 around the centre for breathing room in round masks.
X0, X1, Y0, Y1, GAP, BAR, R, SCALE = 29, 79, 30, 78, 4, 12, 6, 0.92


def rrect(x, y, w, h, r):
    return (f"M{x + r:.2f},{y:.2f}H{x + w - r:.2f}A{r:.2f},{r:.2f} 0 0 1 {x + w:.2f},{y + r:.2f}V{y + h - r:.2f}"
            f"A{r:.2f},{r:.2f} 0 0 1 {x + w - r:.2f},{y + h:.2f}H{x + r:.2f}A{r:.2f},{r:.2f} 0 0 1 {x:.2f},{y + h - r:.2f}"
            f"V{y + r:.2f}A{r:.2f},{r:.2f} 0 0 1 {x + r:.2f},{y:.2f}Z")


def circle(cx, cy, r):
    return f"M{cx - r:.2f},{cy:.2f}a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0Z"


def chevron(x, cy, a, t):
    """The outline of a round-capped ‹ stroke: tip at (x, cy), arms [a] long in x and y, [t] thick.
    One closed path, so it can be a hole (strokes can't)."""
    h = t / 2
    k = h / math.sqrt(2)
    p0, p1, p2 = (x + a, cy - a), (x, cy), (x + a, cy + a)
    n1, n2 = (-k, -k), (-k, k)  # outward normals of the two arms

    def at(p, n, s=1):
        return f"{p[0] + s * n[0]:.2f},{p[1] + s * n[1]:.2f}"
    arc = f"A{h:.2f},{h:.2f} 0 0 0 "
    return (f"M{at(p0, n1)}L{at(p1, n1)}{arc}{at(p1, n2)}L{at(p2, n2)}{arc}{at(p2, n2, -1)}"
            f"L{x + h * math.sqrt(2):.2f},{cy:.2f}L{at(p0, n1, -1)}{arc}{at(p0, n1)}Z")


def compartments():
    """Path data of the four compartments, bar first (with its holes)."""
    cy = Y0 + BAR / 2
    bar = (rrect(X0, Y0, X1 - X0, BAR, BAR / 2) + chevron(X0 + 5.2, cy, 3.4, 2.4)
           + "".join(circle(cx, cy, 2.1) for cx in (X1 - 18, X1 - 11.5, X1 - 5)))
    mid, top = (X0 + X1) / 2, Y0 + BAR + GAP
    half = (Y1 - top - GAP) / 2
    return [bar,
            rrect(X0, top, mid - GAP / 2 - X0, Y1 - top, R),
            rrect(mid + GAP / 2, top, X1 - mid - GAP / 2, half, R),
            rrect(mid + GAP / 2, top + half + GAP, X1 - mid - GAP / 2, half, R)]


def gradient(start, end, x1, y1, x2, y2, pad="    "):
    return (f'{pad}<aapt:attr name="android:fillColor">\n'
            f'{pad}  <gradient android:type="linear" android:startX="{x1}" android:startY="{y1}" android:endX="{x2}" android:endY="{y2}"\n'
            f'{pad}      android:startColor="{start}" android:endColor="{end}"/>\n'
            f'{pad}</aapt:attr>\n')


def mark(fill=None, pivot=54, translate=0.0, scale=SCALE):
    """The compartments in a group scaled around the canvas centre. [fill] = one colour, else the food gradients."""
    out = (f'  <group android:pivotX="{pivot}" android:pivotY="{pivot}" android:scaleX="{scale:.4f}" android:scaleY="{scale:.4f}"'
           f' android:translateX="{translate:.2f}" android:translateY="{translate:.2f}">\n')
    for d, (start, end) in zip(compartments(), FOOD):
        if fill:
            out += f'    <path android:fillColor="{fill}" android:fillType="evenOdd" android:pathData="{d}"/>\n'
        else:
            out += (f'    <path android:fillType="evenOdd" android:pathData="{d}">\n'
                    + gradient(start, end, 0, Y0, 0, Y1, pad="      ")
                    + '    </path>\n')
    return out + '  </group>\n'


def vector(size_dp, viewport, body, tint=False, aapt=False):
    head = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tools/logo.py. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n')
    if aapt:
        head += '    xmlns:aapt="http://schemas.android.com/aapt"\n'
    head += f'    android:width="{size_dp}dp" android:height="{size_dp}dp" android:viewportWidth="{viewport}" android:viewportHeight="{viewport}"'
    if tint:
        head += '\n    android:tint="?android:attr/colorControlNormal"'
    return head + ">\n" + body + "</vector>\n"


def svg_icon(size=512):
    """The launcher icon as SVG in a circle mask (what the Googlebook shelf shows)."""
    hexc = lambda c: "#" + c[3:]
    defs = (f'<linearGradient id="bg" x1="18" y1="18" x2="90" y2="90" gradientUnits="userSpaceOnUse">'
            f'<stop offset="0" stop-color="{hexc(INK[0])}"/><stop offset="1" stop-color="{hexc(INK[1])}"/></linearGradient>')
    paths = ""
    for i, (d, (start, end)) in enumerate(zip(compartments(), FOOD)):
        defs += (f'<linearGradient id="f{i}" x1="0" y1="{Y0}" x2="0" y2="{Y1}" gradientUnits="userSpaceOnUse">'
                 f'<stop offset="0" stop-color="{hexc(start)}"/><stop offset="1" stop-color="{hexc(end)}"/></linearGradient>')
        paths += f'<path fill="url(#f{i})" fill-rule="evenodd" d="{d}"/>'
    return (f'<svg xmlns="http://www.w3.org/2000/svg" width="{size}" height="{size}" viewBox="18 18 72 72">'
            f'<defs>{defs}<clipPath id="m"><circle cx="54" cy="54" r="36"/></clipPath></defs>'
            f'<g clip-path="url(#m)"><rect width="108" height="108" fill="url(#bg)"/>'
            f'<g transform="translate(54 54) scale({SCALE}) translate(-54 -54)">{paths}</g></g></svg>')


def main():
    RES.mkdir(parents=True, exist_ok=True)
    (RES / "ic_launcher_background.xml").write_text(vector(108, 108, (
        '  <path android:pathData="M0,0h108v108h-108z">\n' + gradient(*INK, 18, 18, 90, 90) + '  </path>\n'), aapt=True))
    (RES / "ic_launcher_foreground.xml").write_text(vector(108, 108, mark(), aapt=True))
    (RES / "ic_launcher_monochrome.xml").write_text(vector(108, 108, mark("#FFFFFFFF")))
    # 24 dp: the mark (50 x 48 on the 108 grid) scaled to about 21 dp and centred.
    small = mark("@android:color/white", translate=12 - 54, scale=21 / 50)
    (RES / "ic_bentobar.xml").write_text(vector(24, 24, small, tint=True))
    (RES / "ic_tile_bar.xml").write_text(vector(24, 24, small, tint=True))
    for n in ("ic_launcher_background", "ic_launcher_foreground", "ic_launcher_monochrome", "ic_bentobar", "ic_tile_bar"):
        print(f"res/drawable/{n}.xml")

    if shutil.which("rsvg-convert"):
        out = ROOT / "docs/images/icon.png"
        out.parent.mkdir(parents=True, exist_ok=True)
        with tempfile.NamedTemporaryFile("w", suffix=".svg", delete=False) as f:
            f.write(svg_icon())
        subprocess.run(["rsvg-convert", f.name, "-o", str(out)], check=True)
        os.unlink(f.name)
        print(out.relative_to(ROOT))


if __name__ == "__main__":
    main()
