#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Draws DiscoBar's disco-ball icon as Android vector drawables.

The ball is a grid of mirror facets clipped to a circle. Facet edges follow the sine of
longitude and latitude, so facets narrow towards the rim like on a sphere.

Writes app/src/main/res/drawable/:
  ic_launcher_foreground.xml   the ball with a silver shine and two sparkles (adaptive icon, 108 dp)
  ic_launcher_monochrome.xml   the same shapes in one colour (themed icons)
  ic_launcher_background.xml   the night-club gradient
  ic_disco.xml                 a 24 dp single-colour ball for tiles, notifications and the app

    python3 tools/logo.py
"""
import math
import pathlib

ROOT = pathlib.Path(__file__).resolve().parent.parent
RES = ROOT / "app/src/main/res/drawable"


def facets(cx, cy, r, cols=9, rows=9, gap=0.9):
    """Rectangles (x0, y0, x1, y1) of the facets, before clipping to the circle."""
    xs = [cx + r * math.sin(math.radians(-90 + 180 * i / cols)) for i in range(cols + 1)]
    ys = [cy + r * math.sin(math.radians(-90 + 180 * j / rows)) for j in range(rows + 1)]
    out = []
    for j in range(rows):
        for i in range(cols):
            x0, x1 = xs[i] + gap / 2, xs[i + 1] - gap / 2
            y0, y1 = ys[j] + gap / 2, ys[j + 1] - gap / 2
            if x1 - x0 > 0.3 and y1 - y0 > 0.3:
                out.append((x0, y0, x1, y1))
    return out


def rects_path(rects):
    return "".join(f"M{x0:.2f},{y0:.2f}H{x1:.2f}V{y1:.2f}H{x0:.2f}Z" for x0, y0, x1, y1 in rects)


def circle_path(cx, cy, r):
    return f"M{cx - r:.2f},{cy:.2f}a{r:.2f},{r:.2f} 0 1,0 {2 * r:.2f},0a{r:.2f},{r:.2f} 0 1,0 {-2 * r:.2f},0Z"


def sparkle(cx, cy, s):
    """A four-point star."""
    k = s * 0.22
    return (f"M{cx:.2f},{cy - s:.2f}L{cx + k:.2f},{cy - k:.2f}L{cx + s:.2f},{cy:.2f}L{cx + k:.2f},{cy + k:.2f}"
            f"L{cx:.2f},{cy + s:.2f}L{cx - k:.2f},{cy + k:.2f}L{cx - s:.2f},{cy:.2f}L{cx - k:.2f},{cy - k:.2f}Z")


HEADER = '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py: DiscoBar\'s disco ball. -->\n'


def ball(cx, cy, r, fill, cols, gap, extra=""):
    return (f'  <group>\n    <clip-path android:pathData="{circle_path(cx, cy, r)}"/>\n'
            f'    <path android:pathData="{rects_path(facets(cx, cy, r, cols, cols, gap))}"{fill}{extra}</path>\n'
            f'  </group>\n')


def main():
    RES.mkdir(parents=True, exist_ok=True)
    cx, cy, r = 54, 58, 24
    silver = (
        '>\n      <aapt:attr name="android:fillColor">\n'
        f'        <gradient android:type="radial" android:centerX="{cx - 8}" android:centerY="{cy - 9}" android:gradientRadius="30"\n'
        '            android:startColor="#FFFFFFFF" android:centerColor="#FFE3E6F0" android:endColor="#FF9AA3B8"/>\n'
        '      </aapt:attr>\n    ')
    string = f'  <path android:fillColor="#CCFFFFFF" android:pathData="M{cx - 0.8},{cy - r - 12}h1.6v12h-1.6z"/>\n'
    sparkles = (f'  <path android:fillColor="#FFFFFFFF" android:pathData="{sparkle(80, 37, 7)}"/>\n'
                f'  <path android:fillColor="#DDFFFFFF" android:pathData="{sparkle(28, 46, 4.5)}"/>\n')
    (RES / "ic_launcher_foreground.xml").write_text(
        HEADER + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
        + string + ball(cx, cy, r, silver, 9, 0.9) + sparkles + '</vector>\n')

    mono = ' android:fillColor="#FFFFFFFF">\n    '
    (RES / "ic_launcher_monochrome.xml").write_text(
        HEADER + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
        + string + ball(cx, cy, r, mono, 9, 1.1)
        + f'  <path android:fillColor="#FFFFFFFF" android:pathData="{sparkle(80, 37, 7)}"/>\n</vector>\n')

    (RES / "ic_launcher_background.xml").write_text(
        HEADER + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    xmlns:aapt="http://schemas.android.com/aapt"\n'
        '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
        '  <path android:pathData="M0,0h108v108h-108z">\n'
        '    <aapt:attr name="android:fillColor">\n'
        '      <gradient android:type="linear" android:startX="0" android:startY="0" android:endX="108" android:endY="108"\n'
        '          android:startColor="#FF3B1C8C" android:centerColor="#FF8E24AA" android:endColor="#FFE0407E"/>\n'
        '    </aapt:attr>\n  </path>\n</vector>\n')

    # 24 dp: fewer, bigger facets so it still reads as a mirror ball when small.
    (RES / "ic_disco.xml").write_text(
        HEADER + '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp" android:viewportWidth="24" android:viewportHeight="24"\n'
        '    android:tint="?android:attr/colorControlNormal">\n'
        '  <path android:fillColor="@android:color/white" android:pathData="M11.4,1h1.2v3.2h-1.2z"/>\n'
        + ball(12, 13.5, 9.5, ' android:fillColor="@android:color/white">\n    ', 6, 0.9)
        + f'  <path android:fillColor="@android:color/white" android:pathData="{sparkle(20.5, 4.5, 2.8)}"/>\n</vector>\n')
    for n in ("ic_launcher_foreground", "ic_launcher_monochrome", "ic_launcher_background", "ic_disco"):
        print(f"res/drawable/{n}.xml")


if __name__ == "__main__":
    main()
